// Code generated by the Lingua Franca compiler from:
// file://home/lambrian/149-selfparking-car/src/LineDisplay.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void lf_set_default_command_line_options() {}
#include "_line.h"
#include "_display.h"
#include "_linedisplay_main.h"
typedef enum {
    linedisplay_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[linedisplay_main],"linedisplay_main",linedisplay_main,_lf_number_of_workers,3,2,0,0,7,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `linedisplay_main_downstream`
#define LINEDISPLAY_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int linedisplay_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `linedisplay_main_upstream`
#define LINEDISPLAY_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int linedisplay_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t linedisplay_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case linedisplay_main:
            num_upstream = LINEDISPLAY_MAIN_NUM_UPSTREAM;
            upstream = &linedisplay_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case linedisplay_main:
            num_downstream = LINEDISPLAY_MAIN_NUM_DOWNSTREAM;
            downstream = &linedisplay_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case linedisplay_main:
            num_upstream = LINEDISPLAY_MAIN_NUM_UPSTREAM;
            delay = &linedisplay_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _linedisplay_main_main_self_t* linedisplay_main_self[1];
    SUPPRESS_UNUSED_WARNING(linedisplay_main_self);
    _line_self_t* linedisplay_line_self[1];
    SUPPRESS_UNUSED_WARNING(linedisplay_line_self);
    _display_self_t* linedisplay_disp_self[1];
    SUPPRESS_UNUSED_WARNING(linedisplay_disp_self);
    // ***** Start initializing LineDisplay of class LineDisplay
    linedisplay_main_self[0] = new__linedisplay_main();
    linedisplay_main_self[0]->base.environment = &environments[linedisplay_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    linedisplay_main_self[0]->calibration_time = SEC(10);
    linedisplay_main_self[0]->sample_period = MSEC(100);
    environments[linedisplay_main].startup_reactions[startup_reaction_count[linedisplay_main]++] = &linedisplay_main_self[0]->_lf__reaction_0;
    { // For scoping
        static int _initial = 0;
        linedisplay_main_self[0]->count = _initial;
    } // End scoping.
    // Initiaizing timer LineDisplay.t.
    linedisplay_main_self[0]->_lf__t.offset = 0;
    linedisplay_main_self[0]->_lf__t.period = MSEC(100);
    // Associate timer with the environment of its parent
    environments[linedisplay_main].timer_triggers[timer_triggers_count[linedisplay_main]++] = &linedisplay_main_self[0]->_lf__t;
    linedisplay_main_self[0]->_lf__t.mode = NULL;
    // Initiaizing timer LineDisplay.seconds.
    linedisplay_main_self[0]->_lf__seconds.offset = 0;
    linedisplay_main_self[0]->_lf__seconds.period = SEC(1);
    // Associate timer with the environment of its parent
    environments[linedisplay_main].timer_triggers[timer_triggers_count[linedisplay_main]++] = &linedisplay_main_self[0]->_lf__seconds;
    linedisplay_main_self[0]->_lf__seconds.mode = NULL;
    // Initiaizing timer LineDisplay.end_calibration.
    linedisplay_main_self[0]->_lf__end_calibration.offset = SEC(10);
    linedisplay_main_self[0]->_lf__end_calibration.period = 0;
    // Associate timer with the environment of its parent
    environments[linedisplay_main].timer_triggers[timer_triggers_count[linedisplay_main]++] = &linedisplay_main_self[0]->_lf__end_calibration;
    linedisplay_main_self[0]->_lf__end_calibration.mode = NULL;
    
    linedisplay_main_self[0]->_lf__reaction_0.deadline = NEVER;
    linedisplay_main_self[0]->_lf__reaction_1.deadline = NEVER;
    linedisplay_main_self[0]->_lf__reaction_2.deadline = NEVER;
    linedisplay_main_self[0]->_lf__reaction_3.deadline = NEVER;
    linedisplay_main_self[0]->_lf__reaction_4.deadline = NEVER;
    #if !defined LF_SINGLE_THREADED
    linedisplay_main_self[0]->base.reactor_mutex = NULL;
    #endif
    {
        _linedisplay_main_main_self_t *self = linedisplay_main_self[0];
        // ***** Start initializing LineDisplay.line of class Line
        linedisplay_line_self[0] = new__line();
        linedisplay_line_self[0]->base.environment = &environments[linedisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
                linedisplay_line_self[0]->_lf_reflect.type.element_size = sizeof(uint16_t);
                linedisplay_line_self[0]->_lf_reflect.length = 5;
        // width of -2 indicates that it is not a multiport.
        linedisplay_line_self[0]->_lf_reflect_width = -2;
        // width of -2 indicates that it is not a multiport.
        linedisplay_line_self[0]->_lf_calibrate_width = -2;
        // width of -2 indicates that it is not a multiport.
        linedisplay_line_self[0]->_lf_trigger_width = -2;
        { // For scoping
            static bool _initial = true;
            linedisplay_line_self[0]->calibrating = _initial;
        } // End scoping.
        { // For scoping
            static bool _initial = false;
            linedisplay_line_self[0]->calibrated = _initial;
        } // End scoping.
    
        linedisplay_line_self[0]->_lf__reaction_0.deadline = NEVER;
        linedisplay_line_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        linedisplay_line_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing LineDisplay.line
    }
    {
        _linedisplay_main_main_self_t *self = linedisplay_main_self[0];
        // ***** Start initializing LineDisplay.disp of class Display
        linedisplay_disp_self[0] = new__display();
        linedisplay_disp_self[0]->base.environment = &environments[linedisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        linedisplay_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        linedisplay_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        linedisplay_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        linedisplay_disp_self[0]->_lf_line3_width = -2;
        environments[linedisplay_main].startup_reactions[startup_reaction_count[linedisplay_main]++] = &linedisplay_disp_self[0]->_lf__reaction_0;
    
        linedisplay_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        linedisplay_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        linedisplay_disp_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing LineDisplay.disp
    }
    //***** End initializing LineDisplay
    // **** Start deferred initialize for LineDisplay
    {
        linedisplay_main_self[0]->base.name = "LineDisplay";
        linedisplay_main_self[0]->base.parent = (self_base_t*)NULL;
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of LineDisplay.
        linedisplay_main_self[0]->_lf__reaction_0.num_outputs = 3;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        linedisplay_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                3, sizeof(trigger_t**),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                3, sizeof(int),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                3, sizeof(bool*),
                &linedisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_0.output_produced[count++] = &linedisplay_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_0.output_produced[count++] = &linedisplay_main_self[0]->_lf_disp.line1.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_0.output_produced[count++] = &linedisplay_main_self[0]->_lf_disp.line2.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of LineDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of LineDisplay.
        linedisplay_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        linedisplay_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &linedisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_1.output_produced[count++] = &linedisplay_main_self[0]->_lf_disp.line3.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of LineDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of LineDisplay.
        linedisplay_main_self[0]->_lf__reaction_2.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        linedisplay_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_2.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &linedisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_2.output_produced[count++] = &linedisplay_main_self[0]->_lf_line.calibrate.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of LineDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_4 of LineDisplay.
        linedisplay_main_self[0]->_lf__reaction_3.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        linedisplay_main_self[0]->_lf__reaction_3.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_3.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_3.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &linedisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_3.output_produced[count++] = &linedisplay_main_self[0]->_lf_line.trigger.is_present;
            }
        }
        
        // ** End initialization for reaction 3 of LineDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_5 of LineDisplay.
        linedisplay_main_self[0]->_lf__reaction_4.num_outputs = 3;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        linedisplay_main_self[0]->_lf__reaction_4.triggers = (trigger_t***)lf_allocate(
                3, sizeof(trigger_t**),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_4.triggered_sizes = (int*)lf_allocate(
                3, sizeof(int),
                &linedisplay_main_self[0]->base.allocations);
        linedisplay_main_self[0]->_lf__reaction_4.output_produced = (bool**)lf_allocate(
                3, sizeof(bool*),
                &linedisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_4.output_produced[count++] = &linedisplay_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_4.output_produced[count++] = &linedisplay_main_self[0]->_lf_disp.line1.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                linedisplay_main_self[0]->_lf__reaction_4.output_produced[count++] = &linedisplay_main_self[0]->_lf_disp.line2.is_present;
            }
        }
        
        // ** End initialization for reaction 4 of LineDisplay
    
        // **** Start deferred initialize for LineDisplay.line
        {
            linedisplay_line_self[0]->base.name = "line";
            linedisplay_line_self[0]->base.parent = (self_base_t*)linedisplay_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of LineDisplay.line.
            linedisplay_line_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of LineDisplay.line
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of LineDisplay.line.
            linedisplay_line_self[0]->_lf__reaction_1.num_outputs = 1;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            linedisplay_line_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                    1, sizeof(trigger_t**),
                    &linedisplay_line_self[0]->base.allocations);
            linedisplay_line_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                    1, sizeof(int),
                    &linedisplay_line_self[0]->base.allocations);
            linedisplay_line_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                    1, sizeof(bool*),
                    &linedisplay_line_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    linedisplay_line_self[0]->_lf__reaction_1.output_produced[count++] = &linedisplay_line_self[0]->_lf_reflect.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of LineDisplay.line
        
        }
        // **** End of deferred initialize for LineDisplay.line
        // **** Start deferred initialize for LineDisplay.disp
        {
            linedisplay_disp_self[0]->base.name = "disp";
            linedisplay_disp_self[0]->base.parent = (self_base_t*)linedisplay_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of LineDisplay.disp.
            linedisplay_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of LineDisplay.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of LineDisplay.disp.
            linedisplay_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of LineDisplay.disp
        
        }
        // **** End of deferred initialize for LineDisplay.disp
    }
    // **** End of deferred initialize for LineDisplay
    // **** Start non-nested deferred initialize for LineDisplay
    {
        // Set number of destination reactors for port disp.line0.
        // Iterate over range LineDisplay.disp.line0(0,1)->[LineDisplay.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
            linedisplay_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)linedisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line1.
        // Iterate over range LineDisplay.disp.line1(0,1)->[LineDisplay.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
            linedisplay_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)linedisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line2.
        // Iterate over range LineDisplay.disp.line2(0,1)->[LineDisplay.disp.line2(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_main_self[src_runtime]->_lf_disp.line2._base.num_destinations = 1;
            linedisplay_main_self[src_runtime]->_lf_disp.line2._base.source_reactor = (self_base_t*)linedisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line3.
        // Iterate over range LineDisplay.disp.line3(0,1)->[LineDisplay.disp.line3(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_main_self[src_runtime]->_lf_disp.line3._base.num_destinations = 1;
            linedisplay_main_self[src_runtime]->_lf_disp.line3._base.source_reactor = (self_base_t*)linedisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port line.calibrate.
        // Iterate over range LineDisplay.line.calibrate(0,1)->[LineDisplay.line.calibrate(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_main_self[src_runtime]->_lf_line.calibrate._base.num_destinations = 1;
            linedisplay_main_self[src_runtime]->_lf_line.calibrate._base.source_reactor = (self_base_t*)linedisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port line.trigger.
        // Iterate over range LineDisplay.line.trigger(0,1)->[LineDisplay.line.trigger(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_main_self[src_runtime]->_lf_line.trigger._base.num_destinations = 1;
            linedisplay_main_self[src_runtime]->_lf_line.trigger._base.source_reactor = (self_base_t*)linedisplay_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range LineDisplay.disp.line0(0,1)->[LineDisplay.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.disp.line0.
                linedisplay_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.disp.line0
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range LineDisplay.disp.line1(0,1)->[LineDisplay.disp.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.disp.line1.
                linedisplay_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.disp.line1
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range LineDisplay.disp.line2(0,1)->[LineDisplay.disp.line2(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.disp.line2.
                linedisplay_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.disp.line2
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges LineDisplay.disp.line0(0,1)->[LineDisplay.disp.line0(0,1)] and LineDisplay.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.disp.line0's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_disp_self[dst_runtime]->_lf__line0;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 1;
            // Iterate over ranges LineDisplay.disp.line1(0,1)->[LineDisplay.disp.line1(0,1)] and LineDisplay.disp.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.disp.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.disp.line1's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_disp_self[dst_runtime]->_lf__line1;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 2;
            // Iterate over ranges LineDisplay.disp.line2(0,1)->[LineDisplay.disp.line2(0,1)] and LineDisplay.disp.line2(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.disp.line2(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.disp.line2's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_disp_self[dst_runtime]->_lf__line2;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range LineDisplay.disp.line3(0,1)->[LineDisplay.disp.line3(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.disp.line3.
                linedisplay_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.disp.line3
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges LineDisplay.disp.line3(0,1)->[LineDisplay.disp.line3(0,1)] and LineDisplay.disp.line3(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.disp.line3(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.disp.line3's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_disp_self[dst_runtime]->_lf__line3;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range LineDisplay.line.calibrate(0,1)->[LineDisplay.line.calibrate(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 2 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.line.calibrate.
                linedisplay_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 2 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.line.calibrate
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges LineDisplay.line.calibrate(0,1)->[LineDisplay.line.calibrate(0,1)] and LineDisplay.line.calibrate(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.line.calibrate(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.line.calibrate's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_line_self[dst_runtime]->_lf__calibrate;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range LineDisplay.line.trigger(0,1)->[LineDisplay.line.trigger(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 3 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.line.trigger.
                linedisplay_main_self[src_runtime]->_lf__reaction_3.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 3 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.line.trigger
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges LineDisplay.line.trigger(0,1)->[LineDisplay.line.trigger(0,1)] and LineDisplay.line.trigger(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.line.trigger(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.line.trigger's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_3.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_line_self[dst_runtime]->_lf__trigger;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range LineDisplay.disp.line0(0,1)->[LineDisplay.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 4 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.disp.line0.
                linedisplay_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 4 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.disp.line0
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range LineDisplay.disp.line1(0,1)->[LineDisplay.disp.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 4 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.disp.line1.
                linedisplay_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 4 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.disp.line1
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range LineDisplay.disp.line2(0,1)->[LineDisplay.disp.line2(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 4 of LineDisplay triggers 1 downstream reactions
                // through port LineDisplay.disp.line2.
                linedisplay_main_self[src_runtime]->_lf__reaction_4.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 4 of LineDisplay, allocate an
                // array of trigger pointers for downstream reactions through port LineDisplay.disp.line2
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &linedisplay_main_self[src_runtime]->base.allocations); 
                linedisplay_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges LineDisplay.disp.line0(0,1)->[LineDisplay.disp.line0(0,1)] and LineDisplay.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.disp.line0's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_disp_self[dst_runtime]->_lf__line0;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 1;
            // Iterate over ranges LineDisplay.disp.line1(0,1)->[LineDisplay.disp.line1(0,1)] and LineDisplay.disp.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.disp.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.disp.line1's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_disp_self[dst_runtime]->_lf__line1;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 2;
            // Iterate over ranges LineDisplay.disp.line2(0,1)->[LineDisplay.disp.line2(0,1)] and LineDisplay.disp.line2(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range LineDisplay.disp.line2(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port LineDisplay.disp.line2's trigger struct.
                    linedisplay_main_self[src_runtime]->_lf__reaction_4.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_disp_self[dst_runtime]->_lf__line2;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for LineDisplay.line
        {
        
            // For reference counting, set num_destinations for port LineDisplay.line.reflect.
            // Iterate over range LineDisplay.line.reflect(0,1)->[LineDisplay.line.reflect(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                linedisplay_line_self[src_runtime]->_lf_reflect._base.num_destinations = 1;
                linedisplay_line_self[src_runtime]->_lf_reflect._base.source_reactor = (self_base_t*)linedisplay_line_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range LineDisplay.line.reflect(0,1)->[LineDisplay.line.reflect(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of LineDisplay.line triggers 1 downstream reactions
                    // through port LineDisplay.line.reflect.
                    linedisplay_line_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of LineDisplay.line, allocate an
                    // array of trigger pointers for downstream reactions through port LineDisplay.line.reflect
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &linedisplay_line_self[src_runtime]->base.allocations); 
                    linedisplay_line_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges LineDisplay.line.reflect(0,1)->[LineDisplay.line.reflect(0,1)] and LineDisplay.line.reflect(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range LineDisplay.line.reflect(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port LineDisplay.line.reflect has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        linedisplay_line_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &linedisplay_main_self[dst_runtime]->_lf_line.reflect_trigger;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for LineDisplay.line
        // **** Start non-nested deferred initialize for LineDisplay.disp
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for LineDisplay.disp
    }
    // **** End of non-nested deferred initialize for LineDisplay
    // Connect inputs and outputs for reactor LineDisplay.
    // Connect inputs and outputs for reactor LineDisplay.line.
    // Connect LineDisplay.line.calibrate(0,1)->[LineDisplay.line.calibrate(0,1)] to port LineDisplay.line.calibrate(0,1)
    // Iterate over ranges LineDisplay.line.calibrate(0,1)->[LineDisplay.line.calibrate(0,1)] and LineDisplay.line.calibrate(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range LineDisplay.line.calibrate(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_line_self[dst_runtime]->_lf_calibrate = (_line_calibrate_t*)&linedisplay_main_self[src_runtime]->_lf_line.calibrate;
        }
    }
    // Connect LineDisplay.line.trigger(0,1)->[LineDisplay.line.trigger(0,1)] to port LineDisplay.line.trigger(0,1)
    // Iterate over ranges LineDisplay.line.trigger(0,1)->[LineDisplay.line.trigger(0,1)] and LineDisplay.line.trigger(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range LineDisplay.line.trigger(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_line_self[dst_runtime]->_lf_trigger = (_line_trigger_t*)&linedisplay_main_self[src_runtime]->_lf_line.trigger;
        }
    }
    // Connect LineDisplay.line.reflect(0,1)->[LineDisplay.line.reflect(0,1)] to port LineDisplay.line.reflect(0,1)
    // Iterate over ranges LineDisplay.line.reflect(0,1)->[LineDisplay.line.reflect(0,1)] and LineDisplay.line.reflect(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range LineDisplay.line.reflect(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_main_self[dst_runtime]->_lf_line.reflect = (_line_reflect_t*)&linedisplay_line_self[src_runtime]->_lf_reflect;
        }
    }
    // Connect inputs and outputs for reactor LineDisplay.disp.
    // Connect LineDisplay.disp.line0(0,1)->[LineDisplay.disp.line0(0,1)] to port LineDisplay.disp.line0(0,1)
    // Iterate over ranges LineDisplay.disp.line0(0,1)->[LineDisplay.disp.line0(0,1)] and LineDisplay.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range LineDisplay.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&linedisplay_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect LineDisplay.disp.line1(0,1)->[LineDisplay.disp.line1(0,1)] to port LineDisplay.disp.line1(0,1)
    // Iterate over ranges LineDisplay.disp.line1(0,1)->[LineDisplay.disp.line1(0,1)] and LineDisplay.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range LineDisplay.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&linedisplay_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    // Connect LineDisplay.disp.line2(0,1)->[LineDisplay.disp.line2(0,1)] to port LineDisplay.disp.line2(0,1)
    // Iterate over ranges LineDisplay.disp.line2(0,1)->[LineDisplay.disp.line2(0,1)] and LineDisplay.disp.line2(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range LineDisplay.disp.line2(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_disp_self[dst_runtime]->_lf_line2 = (_display_line2_t*)&linedisplay_main_self[src_runtime]->_lf_disp.line2;
        }
    }
    // Connect LineDisplay.disp.line3(0,1)->[LineDisplay.disp.line3(0,1)] to port LineDisplay.disp.line3(0,1)
    // Iterate over ranges LineDisplay.disp.line3(0,1)->[LineDisplay.disp.line3(0,1)] and LineDisplay.disp.line3(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range LineDisplay.disp.line3(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            linedisplay_disp_self[dst_runtime]->_lf_line3 = (_display_line3_t*)&linedisplay_main_self[src_runtime]->_lf_disp.line3;
        }
    }
    {
    }
    {
    }
    // Add port LineDisplay.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[linedisplay_main].is_present_fields[0 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[linedisplay_main]._lf_intended_tag_fields[0 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port LineDisplay.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[linedisplay_main].is_present_fields[1 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[linedisplay_main]._lf_intended_tag_fields[1 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port LineDisplay.disp.line2 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[linedisplay_main].is_present_fields[2 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_disp.line2.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[linedisplay_main]._lf_intended_tag_fields[2 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_disp.line2.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port LineDisplay.disp.line3 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[linedisplay_main].is_present_fields[3 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_disp.line3.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[linedisplay_main]._lf_intended_tag_fields[3 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_disp.line3.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port LineDisplay.line.calibrate to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[linedisplay_main].is_present_fields[4 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_line.calibrate.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[linedisplay_main]._lf_intended_tag_fields[4 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_line.calibrate.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port LineDisplay.line.trigger to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[linedisplay_main].is_present_fields[5 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_line.trigger.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[linedisplay_main]._lf_intended_tag_fields[5 + (0) * 1 + count] = &linedisplay_main_self[0]->_lf_line.trigger.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port LineDisplay.line.reflect to array of is_present fields.
            environments[linedisplay_main].is_present_fields[(0) * 1 + 6 + count] = &linedisplay_line_self[0]->_lf_reflect.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port LineDisplay.line.reflect to array of intended_tag fields.
            environments[linedisplay_main]._lf_intended_tag_fields[(0) * 1 + 6 + count] = &linedisplay_line_self[0]->_lf_reflect.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance LineDisplay
    {
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        linedisplay_main_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        linedisplay_main_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        linedisplay_main_self[0]->_lf__reaction_2.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        // index is the OR of level 3 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        linedisplay_main_self[0]->_lf__reaction_3.index = lf_combine_deadline_and_level(9223372036854775807, 3);
        // index is the OR of level 5 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        linedisplay_main_self[0]->_lf__reaction_4.index = lf_combine_deadline_and_level(9223372036854775807, 5);
    
        // Set reaction priorities for ReactorInstance LineDisplay.line
        {
            // index is the OR of level 3 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            linedisplay_line_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 3);
            // index is the OR of level 4 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            linedisplay_line_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 4);
        }
    
    
        // Set reaction priorities for ReactorInstance LineDisplay.disp
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            linedisplay_disp_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 6 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            linedisplay_disp_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 6);
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
