// Code generated by the Lingua Franca compiler from:
// file://home/lambrian/149-selfparking-car/src/BumpDisplay.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void lf_set_default_command_line_options() {}
#include "_bump.h"
#include "_display.h"
#include "_bumpdisplay_main.h"
typedef enum {
    bumpdisplay_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[bumpdisplay_main],"bumpdisplay_main",bumpdisplay_main,_lf_number_of_workers,1,2,0,0,5,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `bumpdisplay_main_downstream`
#define BUMPDISPLAY_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int bumpdisplay_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `bumpdisplay_main_upstream`
#define BUMPDISPLAY_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int bumpdisplay_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t bumpdisplay_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case bumpdisplay_main:
            num_upstream = BUMPDISPLAY_MAIN_NUM_UPSTREAM;
            upstream = &bumpdisplay_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case bumpdisplay_main:
            num_downstream = BUMPDISPLAY_MAIN_NUM_DOWNSTREAM;
            downstream = &bumpdisplay_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case bumpdisplay_main:
            num_upstream = BUMPDISPLAY_MAIN_NUM_UPSTREAM;
            delay = &bumpdisplay_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _bumpdisplay_main_main_self_t* bumpdisplay_main_self[1];
    SUPPRESS_UNUSED_WARNING(bumpdisplay_main_self);
    _bump_self_t* bumpdisplay_bump_self[1];
    SUPPRESS_UNUSED_WARNING(bumpdisplay_bump_self);
    _display_self_t* bumpdisplay_disp_self[1];
    SUPPRESS_UNUSED_WARNING(bumpdisplay_disp_self);
    // ***** Start initializing BumpDisplay of class BumpDisplay
    bumpdisplay_main_self[0] = new__bumpdisplay_main();
    bumpdisplay_main_self[0]->base.environment = &environments[bumpdisplay_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    // Initializing action BumpDisplay.clear
    bumpdisplay_main_self[0]->_lf__clear.offset = 0;
    bumpdisplay_main_self[0]->_lf__clear.period = -1;
    bumpdisplay_main_self[0]->_lf__clear.last_tag = NEVER_TAG;
    bumpdisplay_main_self[0]->_lf__clear.mode = NULL;
    _lf_initialize_template((token_template_t*)
            &(bumpdisplay_main_self[0]->_lf__clear),
    0);
    _lf_initialize_template((token_template_t*)
            &(bumpdisplay_main_self[0]->_lf_clear),
    0);
    bumpdisplay_main_self[0]->_lf__clear.status = absent;
    bumpdisplay_main_self[0]->_lf__reaction_0.deadline = NEVER;
    bumpdisplay_main_self[0]->_lf__reaction_1.deadline = NEVER;
    bumpdisplay_main_self[0]->_lf__reaction_2.deadline = NEVER;
    #if !defined LF_SINGLE_THREADED
    bumpdisplay_main_self[0]->base.reactor_mutex = NULL;
    #endif
    {
        _bumpdisplay_main_main_self_t *self = bumpdisplay_main_self[0];
        // ***** Start initializing BumpDisplay.bump of class Bump
        bumpdisplay_bump_self[0] = new__bump();
        bumpdisplay_bump_self[0]->base.environment = &environments[bumpdisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        bumpdisplay_bump_self[0]->sample_period = MSEC(100);
        
        
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_bump_self[0]->_lf_left_width = -2;
        
        
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_bump_self[0]->_lf_right_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_bump_self[0]->_lf_calibrate_width = -2;
        environments[bumpdisplay_main].startup_reactions[startup_reaction_count[bumpdisplay_main]++] = &bumpdisplay_bump_self[0]->_lf__reaction_0;
        // Initiaizing timer BumpDisplay.bump.t1.
        bumpdisplay_bump_self[0]->_lf__t1.offset = 0;
        bumpdisplay_bump_self[0]->_lf__t1.period = MSEC(100);
        // Associate timer with the environment of its parent
        environments[bumpdisplay_main].timer_triggers[timer_triggers_count[bumpdisplay_main]++] = &bumpdisplay_bump_self[0]->_lf__t1;
        bumpdisplay_bump_self[0]->_lf__t1.mode = NULL;
    
        bumpdisplay_bump_self[0]->_lf__reaction_0.deadline = NEVER;
        bumpdisplay_bump_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        bumpdisplay_bump_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing BumpDisplay.bump
    }
    {
        _bumpdisplay_main_main_self_t *self = bumpdisplay_main_self[0];
        // ***** Start initializing BumpDisplay.disp of class Display
        bumpdisplay_disp_self[0] = new__display();
        bumpdisplay_disp_self[0]->base.environment = &environments[bumpdisplay_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        bumpdisplay_disp_self[0]->_lf_line3_width = -2;
        environments[bumpdisplay_main].startup_reactions[startup_reaction_count[bumpdisplay_main]++] = &bumpdisplay_disp_self[0]->_lf__reaction_0;
    
        bumpdisplay_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        bumpdisplay_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        bumpdisplay_disp_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing BumpDisplay.disp
    }
    //***** End initializing BumpDisplay
    // **** Start deferred initialize for BumpDisplay
    {
        bumpdisplay_main_self[0]->base.name = "BumpDisplay";
        bumpdisplay_main_self[0]->base.parent = (self_base_t*)NULL;
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of BumpDisplay.
        bumpdisplay_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bumpdisplay_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &bumpdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bumpdisplay_main_self[0]->_lf__reaction_0.output_produced[count++] = &bumpdisplay_main_self[0]->_lf_disp.line0.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of BumpDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of BumpDisplay.
        bumpdisplay_main_self[0]->_lf__reaction_1.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bumpdisplay_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &bumpdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bumpdisplay_main_self[0]->_lf__reaction_1.output_produced[count++] = &bumpdisplay_main_self[0]->_lf_disp.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of BumpDisplay
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_3 of BumpDisplay.
        bumpdisplay_main_self[0]->_lf__reaction_2.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        bumpdisplay_main_self[0]->_lf__reaction_2.triggers = (trigger_t***)lf_allocate(
                2, sizeof(trigger_t**),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_2.triggered_sizes = (int*)lf_allocate(
                2, sizeof(int),
                &bumpdisplay_main_self[0]->base.allocations);
        bumpdisplay_main_self[0]->_lf__reaction_2.output_produced = (bool**)lf_allocate(
                2, sizeof(bool*),
                &bumpdisplay_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                bumpdisplay_main_self[0]->_lf__reaction_2.output_produced[count++] = &bumpdisplay_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                bumpdisplay_main_self[0]->_lf__reaction_2.output_produced[count++] = &bumpdisplay_main_self[0]->_lf_disp.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 2 of BumpDisplay
    
        // **** Start deferred initialize for BumpDisplay.bump
        {
            bumpdisplay_bump_self[0]->base.name = "bump";
            bumpdisplay_bump_self[0]->base.parent = (self_base_t*)bumpdisplay_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of BumpDisplay.bump.
            bumpdisplay_bump_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of BumpDisplay.bump
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of BumpDisplay.bump.
            bumpdisplay_bump_self[0]->_lf__reaction_1.num_outputs = 2;
            // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
            // struct for this reaction.
            bumpdisplay_bump_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                    2, sizeof(trigger_t**),
                    &bumpdisplay_bump_self[0]->base.allocations);
            bumpdisplay_bump_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                    2, sizeof(int),
                    &bumpdisplay_bump_self[0]->base.allocations);
            bumpdisplay_bump_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                    2, sizeof(bool*),
                    &bumpdisplay_bump_self[0]->base.allocations);
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
                {
                    bumpdisplay_bump_self[0]->_lf__reaction_1.output_produced[count++] = &bumpdisplay_bump_self[0]->_lf_left.is_present;
                }
                {
                    bumpdisplay_bump_self[0]->_lf__reaction_1.output_produced[count++] = &bumpdisplay_bump_self[0]->_lf_right.is_present;
                }
            }
            
            // ** End initialization for reaction 1 of BumpDisplay.bump
        
        }
        // **** End of deferred initialize for BumpDisplay.bump
        // **** Start deferred initialize for BumpDisplay.disp
        {
            bumpdisplay_disp_self[0]->base.name = "disp";
            bumpdisplay_disp_self[0]->base.parent = (self_base_t*)bumpdisplay_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of BumpDisplay.disp.
            bumpdisplay_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of BumpDisplay.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of BumpDisplay.disp.
            bumpdisplay_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of BumpDisplay.disp
        
        }
        // **** End of deferred initialize for BumpDisplay.disp
    }
    // **** End of deferred initialize for BumpDisplay
    // **** Start non-nested deferred initialize for BumpDisplay
    {
        // Set number of destination reactors for port disp.line0.
        // Iterate over range BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
            bumpdisplay_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)bumpdisplay_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line1.
        // Iterate over range BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
            bumpdisplay_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)bumpdisplay_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of BumpDisplay triggers 1 downstream reactions
                // through port BumpDisplay.disp.line0.
                bumpdisplay_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of BumpDisplay, allocate an
                // array of trigger pointers for downstream reactions through port BumpDisplay.disp.line0
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &bumpdisplay_main_self[src_runtime]->base.allocations); 
                bumpdisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)] and BumpDisplay.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range BumpDisplay.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port BumpDisplay.disp.line0's trigger struct.
                    bumpdisplay_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_disp_self[dst_runtime]->_lf__line0;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of BumpDisplay triggers 1 downstream reactions
                // through port BumpDisplay.disp.line1.
                bumpdisplay_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of BumpDisplay, allocate an
                // array of trigger pointers for downstream reactions through port BumpDisplay.disp.line1
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &bumpdisplay_main_self[src_runtime]->base.allocations); 
                bumpdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)] and BumpDisplay.disp.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range BumpDisplay.disp.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port BumpDisplay.disp.line1's trigger struct.
                    bumpdisplay_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_disp_self[dst_runtime]->_lf__line1;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 2 of BumpDisplay triggers 1 downstream reactions
                // through port BumpDisplay.disp.line0.
                bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 2 of BumpDisplay, allocate an
                // array of trigger pointers for downstream reactions through port BumpDisplay.disp.line0
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &bumpdisplay_main_self[src_runtime]->base.allocations); 
                bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 2 of BumpDisplay triggers 1 downstream reactions
                // through port BumpDisplay.disp.line1.
                bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 2 of BumpDisplay, allocate an
                // array of trigger pointers for downstream reactions through port BumpDisplay.disp.line1
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &bumpdisplay_main_self[src_runtime]->base.allocations); 
                bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)] and BumpDisplay.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range BumpDisplay.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port BumpDisplay.disp.line0's trigger struct.
                    bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_disp_self[dst_runtime]->_lf__line0;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 1;
            // Iterate over ranges BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)] and BumpDisplay.disp.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range BumpDisplay.disp.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port BumpDisplay.disp.line1's trigger struct.
                    bumpdisplay_main_self[src_runtime]->_lf__reaction_2.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_disp_self[dst_runtime]->_lf__line1;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for BumpDisplay.bump
        {
        
            // For reference counting, set num_destinations for port BumpDisplay.bump.left.
            // Iterate over range BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                bumpdisplay_bump_self[src_runtime]->_lf_left._base.num_destinations = 1;
                bumpdisplay_bump_self[src_runtime]->_lf_left._base.source_reactor = (self_base_t*)bumpdisplay_bump_self[src_runtime];
            }
            // For reference counting, set num_destinations for port BumpDisplay.bump.right.
            // Iterate over range BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                bumpdisplay_bump_self[src_runtime]->_lf_right._base.num_destinations = 1;
                bumpdisplay_bump_self[src_runtime]->_lf_right._base.source_reactor = (self_base_t*)bumpdisplay_bump_self[src_runtime];
            }
            {
                int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
                // Iterate over range BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of BumpDisplay.bump triggers 1 downstream reactions
                    // through port BumpDisplay.bump.left.
                    bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of BumpDisplay.bump, allocate an
                    // array of trigger pointers for downstream reactions through port BumpDisplay.bump.left
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &bumpdisplay_bump_self[src_runtime]->base.allocations); 
                    bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                // Iterate over range BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)].
                {
                    int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                    int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                    int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Reaction 1 of BumpDisplay.bump triggers 1 downstream reactions
                    // through port BumpDisplay.bump.right.
                    bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                    // For reaction 1 of BumpDisplay.bump, allocate an
                    // array of trigger pointers for downstream reactions through port BumpDisplay.bump.right
                    trigger_t** trigger_array = (trigger_t**)lf_allocate(
                            1, sizeof(trigger_t*),
                            &bumpdisplay_bump_self[src_runtime]->base.allocations); 
                    bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 0;
                // Iterate over ranges BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)] and BumpDisplay.bump.left(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range BumpDisplay.bump.left(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port BumpDisplay.bump.left has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_main_self[dst_runtime]->_lf_bump.left_trigger;
                    }
                }
                for (int i = 0; i < 1; i++) triggers_index[i] = 1;
                // Iterate over ranges BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)] and BumpDisplay.bump.right(0,1).
                {
                    int src_runtime = 0; // Runtime index.
                    SUPPRESS_UNUSED_WARNING(src_runtime);
                    int src_channel = 0; // Channel index.
                    SUPPRESS_UNUSED_WARNING(src_channel);
                    int src_bank = 0; // Bank index.
                    SUPPRESS_UNUSED_WARNING(src_bank);
                    // Iterate over range BumpDisplay.bump.right(0,1).
                    {
                        int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                        int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                        int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                        int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                        // Port BumpDisplay.bump.right has reactions in its parent's parent.
                        // Point to the trigger struct for those reactions.
                        bumpdisplay_bump_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &bumpdisplay_main_self[dst_runtime]->_lf_bump.right_trigger;
                    }
                }
            }
        
        }
        // **** End of non-nested deferred initialize for BumpDisplay.bump
        // **** Start non-nested deferred initialize for BumpDisplay.disp
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for BumpDisplay.disp
    }
    // **** End of non-nested deferred initialize for BumpDisplay
    // Connect inputs and outputs for reactor BumpDisplay.
    // Connect inputs and outputs for reactor BumpDisplay.bump.
    // Connect BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)] to port BumpDisplay.bump.left(0,1)
    // Iterate over ranges BumpDisplay.bump.left(0,1)->[BumpDisplay.bump.left(0,1)] and BumpDisplay.bump.left(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range BumpDisplay.bump.left(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_main_self[dst_runtime]->_lf_bump.left = (_bump_left_t*)&bumpdisplay_bump_self[src_runtime]->_lf_left;
        }
    }
    // Connect BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)] to port BumpDisplay.bump.right(0,1)
    // Iterate over ranges BumpDisplay.bump.right(0,1)->[BumpDisplay.bump.right(0,1)] and BumpDisplay.bump.right(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range BumpDisplay.bump.right(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_main_self[dst_runtime]->_lf_bump.right = (_bump_right_t*)&bumpdisplay_bump_self[src_runtime]->_lf_right;
        }
    }
    // Connect inputs and outputs for reactor BumpDisplay.disp.
    // Connect BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)] to port BumpDisplay.disp.line0(0,1)
    // Iterate over ranges BumpDisplay.disp.line0(0,1)->[BumpDisplay.disp.line0(0,1)] and BumpDisplay.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range BumpDisplay.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&bumpdisplay_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)] to port BumpDisplay.disp.line1(0,1)
    // Iterate over ranges BumpDisplay.disp.line1(0,1)->[BumpDisplay.disp.line1(0,1)] and BumpDisplay.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range BumpDisplay.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            bumpdisplay_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&bumpdisplay_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    {
    }
    {
    }
    // Add port BumpDisplay.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[bumpdisplay_main].is_present_fields[0 + (0) * 1 + count] = &bumpdisplay_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[bumpdisplay_main]._lf_intended_tag_fields[0 + (0) * 1 + count] = &bumpdisplay_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port BumpDisplay.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[bumpdisplay_main].is_present_fields[1 + (0) * 1 + count] = &bumpdisplay_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[bumpdisplay_main]._lf_intended_tag_fields[1 + (0) * 1 + count] = &bumpdisplay_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add action BumpDisplay.clear to array of is_present fields.
    environments[bumpdisplay_main].is_present_fields[2 + (0) * 1]
            = (bool *) &bumpdisplay_main_self[0]->_lf__clear.status;
    #ifdef FEDERATED_DECENTRALIZED
    // Add action BumpDisplay.clear to array of intended_tag fields.
    environments[bumpdisplay_main]._lf_intended_tag_fields[2 + (0) * 1]
            = &bumpdisplay_main_self[0]->_lf_clear.intended_tag;
    #endif // FEDERATED_DECENTRALIZED
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            // Add output port BumpDisplay.bump.left to array of is_present fields.
            environments[bumpdisplay_main].is_present_fields[(0) * 2 + 3 + count] = &bumpdisplay_bump_self[0]->_lf_left.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port BumpDisplay.bump.left to array of intended_tag fields.
            environments[bumpdisplay_main]._lf_intended_tag_fields[(0) * 2 + 3 + count] = &bumpdisplay_bump_self[0]->_lf_left.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
            // Add output port BumpDisplay.bump.right to array of is_present fields.
            environments[bumpdisplay_main].is_present_fields[(0) * 2 + 3 + count] = &bumpdisplay_bump_self[0]->_lf_right.is_present;
            #ifdef FEDERATED_DECENTRALIZED
            // Add output port BumpDisplay.bump.right to array of intended_tag fields.
            environments[bumpdisplay_main]._lf_intended_tag_fields[(0) * 2 + 3 + count] = &bumpdisplay_bump_self[0]->_lf_right.intended_tag;
            #endif // FEDERATED_DECENTRALIZED
            count++;
        }
    }
    
    // Set reaction priorities for ReactorInstance BumpDisplay
    {
        // index is the OR of level 2 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bumpdisplay_main_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        // index is the OR of level 3 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bumpdisplay_main_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 3);
        // index is the OR of level 4 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        bumpdisplay_main_self[0]->_lf__reaction_2.index = lf_combine_deadline_and_level(9223372036854775807, 4);
    
        // Set reaction priorities for ReactorInstance BumpDisplay.bump
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bumpdisplay_bump_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 1 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bumpdisplay_bump_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
        }
    
    
        // Set reaction priorities for ReactorInstance BumpDisplay.disp
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bumpdisplay_disp_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 5 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            bumpdisplay_disp_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 5);
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
