// Code generated by the Lingua Franca compiler from:
// file://home/lambrian/149-selfparking-car/src/I2C_test.lf
#define LOG_LEVEL 2

#include <limits.h>
#include "low_level_platform/api/low_level_platform.h"
#include "include/api/schedule.h"
#include "include/core/reactor.h"
#include "include/core/reactor_common.h"
#include "include/core/mixed_radix.h"
#include "include/core/port.h"
#include "include/core/environment.h"
int lf_reactor_c_main(int argc, const char* argv[]);
int main(void) {
   return lf_reactor_c_main(0, NULL);
}
void lf_set_default_command_line_options() {}
#include "_display.h"
#include "_i2c_test_main.h"
typedef enum {
    i2c_test_main,
    num_environments
} _enclave_id;
// The global array of environments associated with each enclave
static environment_t environments[num_environments];
// 'Create' and initialize the environments in the program
void lf_create_environments() {
    environment_init(&environments[i2c_test_main],"i2c_test_main",i2c_test_main,_lf_number_of_workers,1,2,0,0,2,0,0,0,NULL);
}
// Update the pointer argument to point to the beginning of the environment array
// and return the size of that array
int _lf_get_environments(environment_t ** return_envs) {
   (*return_envs) = (environment_t *) environments;
   return num_environments;
}
// Arrays representing the enclaves downstream of `i2c_test_main_downstream`
#define I2C_TEST_MAIN_NUM_DOWNSTREAM 0
// No downstreams, but 0-length arrays not allowed by MSVC (C2466)
int i2c_test_main_downstream[1] = {-1};
// Arrays representing the enclaves upstream of `i2c_test_main_upstream`
#define I2C_TEST_MAIN_NUM_UPSTREAM 0
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
int i2c_test_main_upstream[1] = {-1};
// No upstreams, but 0-length arrays not allowed by MSVC (C2466)
interval_t i2c_test_main_upstream_delay[1] = {FOREVER};
// Writes a pointer to the array of upstream enclaves into `result` and returns the length
int lf_get_upstream_of(int enclave_id, int ** result) {
    int num_upstream;
    int* upstream;
    switch(enclave_id) { 
        case i2c_test_main:
            num_upstream = I2C_TEST_MAIN_NUM_UPSTREAM;
            upstream = &i2c_test_main_upstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = upstream;
    return num_upstream;
}
// Writes a pointer to the array of downstream enclaves into `result` and returns the length
int lf_get_downstream_of(int enclave_id, int ** result) {
    int num_downstream;
    int* downstream;
    switch(enclave_id) { 
        case i2c_test_main:
            num_downstream = I2C_TEST_MAIN_NUM_DOWNSTREAM;
            downstream = &i2c_test_main_downstream[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = downstream;
    return num_downstream;
}
// Writes a pointer to the array of upstream delays into `result` and returns the length
int lf_get_upstream_delay_of(int enclave_id, interval_t ** result) {
    int num_upstream;
    interval_t* delay;
    switch(enclave_id) { 
        case i2c_test_main:
            num_upstream = I2C_TEST_MAIN_NUM_UPSTREAM;
            delay = &i2c_test_main_upstream_delay[0];
            break;
        default:
            lf_print_error_and_exit("Illegal enclave_id %u", enclave_id);
            break;
        }
    (*result) = delay;
    return num_upstream;
}
void _lf_initialize_trigger_objects() {
    int startup_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(startup_reaction_count);
    int shutdown_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(shutdown_reaction_count);
    int reset_reaction_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(reset_reaction_count);
    int timer_triggers_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(timer_triggers_count);
    int modal_state_reset_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_state_reset_count);
    int modal_reactor_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(modal_reactor_count);
    int watchdog_count[num_environments] = {0}; SUPPRESS_UNUSED_WARNING(watchdog_count);
    int bank_index;
    SUPPRESS_UNUSED_WARNING(bank_index);
    int watchdog_number = 0;
    SUPPRESS_UNUSED_WARNING(watchdog_number);
    _i2c_test_main_main_self_t* i2c_test_main_self[1];
    SUPPRESS_UNUSED_WARNING(i2c_test_main_self);
    _display_self_t* i2c_test_disp_self[1];
    SUPPRESS_UNUSED_WARNING(i2c_test_disp_self);
    // ***** Start initializing I2C_test of class I2C_test
    i2c_test_main_self[0] = new__i2c_test_main();
    i2c_test_main_self[0]->base.environment = &environments[i2c_test_main];
    bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
    environments[i2c_test_main].startup_reactions[startup_reaction_count[i2c_test_main]++] = &i2c_test_main_self[0]->_lf__reaction_0;
    // Initiaizing timer I2C_test.t.
    i2c_test_main_self[0]->_lf__t.offset = 0;
    i2c_test_main_self[0]->_lf__t.period = MSEC(1);
    // Associate timer with the environment of its parent
    environments[i2c_test_main].timer_triggers[timer_triggers_count[i2c_test_main]++] = &i2c_test_main_self[0]->_lf__t;
    i2c_test_main_self[0]->_lf__t.mode = NULL;
    
    i2c_test_main_self[0]->_lf__reaction_0.deadline = NEVER;
    i2c_test_main_self[0]->_lf__reaction_1.deadline = NEVER;
    #if !defined LF_SINGLE_THREADED
    i2c_test_main_self[0]->base.reactor_mutex = NULL;
    #endif
    {
        _i2c_test_main_main_self_t *self = i2c_test_main_self[0];
        // ***** Start initializing I2C_test.disp of class Display
        i2c_test_disp_self[0] = new__display();
        i2c_test_disp_self[0]->base.environment = &environments[i2c_test_main];
        bank_index = 0; SUPPRESS_UNUSED_WARNING(bank_index);
        // width of -2 indicates that it is not a multiport.
        i2c_test_disp_self[0]->_lf_line0_width = -2;
        // width of -2 indicates that it is not a multiport.
        i2c_test_disp_self[0]->_lf_line1_width = -2;
        // width of -2 indicates that it is not a multiport.
        i2c_test_disp_self[0]->_lf_line2_width = -2;
        // width of -2 indicates that it is not a multiport.
        i2c_test_disp_self[0]->_lf_line3_width = -2;
        environments[i2c_test_main].startup_reactions[startup_reaction_count[i2c_test_main]++] = &i2c_test_disp_self[0]->_lf__reaction_0;
    
        i2c_test_disp_self[0]->_lf__reaction_0.deadline = NEVER;
        i2c_test_disp_self[0]->_lf__reaction_1.deadline = NEVER;
        #if !defined LF_SINGLE_THREADED
        i2c_test_disp_self[0]->base.reactor_mutex = NULL;
        #endif
        //***** End initializing I2C_test.disp
    }
    //***** End initializing I2C_test
    // **** Start deferred initialize for I2C_test
    {
        i2c_test_main_self[0]->base.name = "I2C_test";
        i2c_test_main_self[0]->base.parent = (self_base_t*)NULL;
    
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_1 of I2C_test.
        i2c_test_main_self[0]->_lf__reaction_0.num_outputs = 1;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        i2c_test_main_self[0]->_lf__reaction_0.triggers = (trigger_t***)lf_allocate(
                1, sizeof(trigger_t**),
                &i2c_test_main_self[0]->base.allocations);
        i2c_test_main_self[0]->_lf__reaction_0.triggered_sizes = (int*)lf_allocate(
                1, sizeof(int),
                &i2c_test_main_self[0]->base.allocations);
        i2c_test_main_self[0]->_lf__reaction_0.output_produced = (bool**)lf_allocate(
                1, sizeof(bool*),
                &i2c_test_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                i2c_test_main_self[0]->_lf__reaction_0.output_produced[count++] = &i2c_test_main_self[0]->_lf_disp.line0.is_present;
            }
        }
        
        // ** End initialization for reaction 0 of I2C_test
        // Total number of outputs (single ports and multiport channels)
        // produced by reaction_2 of I2C_test.
        i2c_test_main_self[0]->_lf__reaction_1.num_outputs = 2;
        // Allocate memory for triggers[] and triggered_sizes[] on the reaction_t
        // struct for this reaction.
        i2c_test_main_self[0]->_lf__reaction_1.triggers = (trigger_t***)lf_allocate(
                2, sizeof(trigger_t**),
                &i2c_test_main_self[0]->base.allocations);
        i2c_test_main_self[0]->_lf__reaction_1.triggered_sizes = (int*)lf_allocate(
                2, sizeof(int),
                &i2c_test_main_self[0]->base.allocations);
        i2c_test_main_self[0]->_lf__reaction_1.output_produced = (bool**)lf_allocate(
                2, sizeof(bool*),
                &i2c_test_main_self[0]->base.allocations);
        {
            int count = 0; SUPPRESS_UNUSED_WARNING(count);
            // Reaction writes to an input of a contained reactor.
            {
                i2c_test_main_self[0]->_lf__reaction_1.output_produced[count++] = &i2c_test_main_self[0]->_lf_disp.line0.is_present;
            }
            // Reaction writes to an input of a contained reactor.
            {
                i2c_test_main_self[0]->_lf__reaction_1.output_produced[count++] = &i2c_test_main_self[0]->_lf_disp.line1.is_present;
            }
        }
        
        // ** End initialization for reaction 1 of I2C_test
    
        // **** Start deferred initialize for I2C_test.disp
        {
            i2c_test_disp_self[0]->base.name = "disp";
            i2c_test_disp_self[0]->base.parent = (self_base_t*)i2c_test_main_self[0];
        
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_1 of I2C_test.disp.
            i2c_test_disp_self[0]->_lf__reaction_0.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 0 of I2C_test.disp
            // Total number of outputs (single ports and multiport channels)
            // produced by reaction_2 of I2C_test.disp.
            i2c_test_disp_self[0]->_lf__reaction_1.num_outputs = 0;
            {
                int count = 0; SUPPRESS_UNUSED_WARNING(count);
            }
            
            // ** End initialization for reaction 1 of I2C_test.disp
        
        }
        // **** End of deferred initialize for I2C_test.disp
    }
    // **** End of deferred initialize for I2C_test
    // **** Start non-nested deferred initialize for I2C_test
    {
        // Set number of destination reactors for port disp.line0.
        // Iterate over range I2C_test.disp.line0(0,1)->[I2C_test.disp.line0(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            i2c_test_main_self[src_runtime]->_lf_disp.line0._base.num_destinations = 1;
            i2c_test_main_self[src_runtime]->_lf_disp.line0._base.source_reactor = (self_base_t*)i2c_test_main_self[src_runtime];
        }
        // Set number of destination reactors for port disp.line1.
        // Iterate over range I2C_test.disp.line1(0,1)->[I2C_test.disp.line1(0,1)].
        {
            int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
            int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
            int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            i2c_test_main_self[src_runtime]->_lf_disp.line1._base.num_destinations = 1;
            i2c_test_main_self[src_runtime]->_lf_disp.line1._base.source_reactor = (self_base_t*)i2c_test_main_self[src_runtime];
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range I2C_test.disp.line0(0,1)->[I2C_test.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 0 of I2C_test triggers 1 downstream reactions
                // through port I2C_test.disp.line0.
                i2c_test_main_self[src_runtime]->_lf__reaction_0.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 0 of I2C_test, allocate an
                // array of trigger pointers for downstream reactions through port I2C_test.disp.line0
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &i2c_test_main_self[src_runtime]->base.allocations); 
                i2c_test_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges I2C_test.disp.line0(0,1)->[I2C_test.disp.line0(0,1)] and I2C_test.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range I2C_test.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port I2C_test.disp.line0's trigger struct.
                    i2c_test_main_self[src_runtime]->_lf__reaction_0.triggers[triggers_index[src_runtime] + src_channel][0] = &i2c_test_disp_self[dst_runtime]->_lf__line0;
                }
            }
        }
        {
            int triggers_index[1] = { 0 }; // Number of bank members with the reaction.
            // Iterate over range I2C_test.disp.line0(0,1)->[I2C_test.disp.line0(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of I2C_test triggers 1 downstream reactions
                // through port I2C_test.disp.line0.
                i2c_test_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of I2C_test, allocate an
                // array of trigger pointers for downstream reactions through port I2C_test.disp.line0
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &i2c_test_main_self[src_runtime]->base.allocations); 
                i2c_test_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            // Iterate over range I2C_test.disp.line1(0,1)->[I2C_test.disp.line1(0,1)].
            {
                int src_runtime = 0; SUPPRESS_UNUSED_WARNING(src_runtime); // Runtime index.
                int src_channel = 0; SUPPRESS_UNUSED_WARNING(src_channel); // Channel index.
                int src_bank = 0; SUPPRESS_UNUSED_WARNING(src_bank); // Bank index.
                int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                // Reaction 1 of I2C_test triggers 1 downstream reactions
                // through port I2C_test.disp.line1.
                i2c_test_main_self[src_runtime]->_lf__reaction_1.triggered_sizes[triggers_index[src_runtime]] = 1;
                // For reaction 1 of I2C_test, allocate an
                // array of trigger pointers for downstream reactions through port I2C_test.disp.line1
                trigger_t** trigger_array = (trigger_t**)lf_allocate(
                        1, sizeof(trigger_t*),
                        &i2c_test_main_self[src_runtime]->base.allocations); 
                i2c_test_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime]++] = trigger_array;
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 0;
            // Iterate over ranges I2C_test.disp.line0(0,1)->[I2C_test.disp.line0(0,1)] and I2C_test.disp.line0(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range I2C_test.disp.line0(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port I2C_test.disp.line0's trigger struct.
                    i2c_test_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &i2c_test_disp_self[dst_runtime]->_lf__line0;
                }
            }
            for (int i = 0; i < 1; i++) triggers_index[i] = 1;
            // Iterate over ranges I2C_test.disp.line1(0,1)->[I2C_test.disp.line1(0,1)] and I2C_test.disp.line1(0,1).
            {
                int src_runtime = 0; // Runtime index.
                SUPPRESS_UNUSED_WARNING(src_runtime);
                int src_channel = 0; // Channel index.
                SUPPRESS_UNUSED_WARNING(src_channel);
                int src_bank = 0; // Bank index.
                SUPPRESS_UNUSED_WARNING(src_bank);
                // Iterate over range I2C_test.disp.line1(0,1).
                {
                    int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
                    int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
                    int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
                    int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
                    // Point to destination port I2C_test.disp.line1's trigger struct.
                    i2c_test_main_self[src_runtime]->_lf__reaction_1.triggers[triggers_index[src_runtime] + src_channel][0] = &i2c_test_disp_self[dst_runtime]->_lf__line1;
                }
            }
        }
    
        // **** Start non-nested deferred initialize for I2C_test.disp
        {
        
        
        
        
        }
        // **** End of non-nested deferred initialize for I2C_test.disp
    }
    // **** End of non-nested deferred initialize for I2C_test
    // Connect inputs and outputs for reactor I2C_test.
    // Connect inputs and outputs for reactor I2C_test.disp.
    // Connect I2C_test.disp.line0(0,1)->[I2C_test.disp.line0(0,1)] to port I2C_test.disp.line0(0,1)
    // Iterate over ranges I2C_test.disp.line0(0,1)->[I2C_test.disp.line0(0,1)] and I2C_test.disp.line0(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range I2C_test.disp.line0(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            i2c_test_disp_self[dst_runtime]->_lf_line0 = (_display_line0_t*)&i2c_test_main_self[src_runtime]->_lf_disp.line0;
        }
    }
    // Connect I2C_test.disp.line1(0,1)->[I2C_test.disp.line1(0,1)] to port I2C_test.disp.line1(0,1)
    // Iterate over ranges I2C_test.disp.line1(0,1)->[I2C_test.disp.line1(0,1)] and I2C_test.disp.line1(0,1).
    {
        int src_runtime = 0; // Runtime index.
        SUPPRESS_UNUSED_WARNING(src_runtime);
        int src_channel = 0; // Channel index.
        SUPPRESS_UNUSED_WARNING(src_channel);
        int src_bank = 0; // Bank index.
        SUPPRESS_UNUSED_WARNING(src_bank);
        // Iterate over range I2C_test.disp.line1(0,1).
        {
            int dst_runtime = 0; SUPPRESS_UNUSED_WARNING(dst_runtime); // Runtime index.
            int dst_channel = 0; SUPPRESS_UNUSED_WARNING(dst_channel); // Channel index.
            int dst_bank = 0; SUPPRESS_UNUSED_WARNING(dst_bank); // Bank index.
            int range_count = 0; SUPPRESS_UNUSED_WARNING(range_count);
            i2c_test_disp_self[dst_runtime]->_lf_line1 = (_display_line1_t*)&i2c_test_main_self[src_runtime]->_lf_disp.line1;
        }
    }
    {
    }
    // Add port I2C_test.disp.line0 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[i2c_test_main].is_present_fields[0 + (0) * 1 + count] = &i2c_test_main_self[0]->_lf_disp.line0.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[i2c_test_main]._lf_intended_tag_fields[0 + (0) * 1 + count] = &i2c_test_main_self[0]->_lf_disp.line0.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    // Add port I2C_test.disp.line1 to array of is_present fields.
    {
        int count = 0; SUPPRESS_UNUSED_WARNING(count);
        {
            {
                environments[i2c_test_main].is_present_fields[1 + (0) * 1 + count] = &i2c_test_main_self[0]->_lf_disp.line1.is_present;
                #ifdef FEDERATED_DECENTRALIZED
                environments[i2c_test_main]._lf_intended_tag_fields[1 + (0) * 1 + count] = &i2c_test_main_self[0]->_lf_disp.line1.intended_tag;
                #endif // FEDERATED_DECENTRALIZED
                count++;
            }
        }
    }
    
    // Set reaction priorities for ReactorInstance I2C_test
    {
        // index is the OR of level 0 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        i2c_test_main_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
        // index is the OR of level 1 and 
        // deadline 9223372036854775807 shifted left 16 bits.
        i2c_test_main_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 1);
    
        // Set reaction priorities for ReactorInstance I2C_test.disp
        {
            // index is the OR of level 0 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            i2c_test_disp_self[0]->_lf__reaction_0.index = lf_combine_deadline_and_level(9223372036854775807, 0);
            // index is the OR of level 2 and 
            // deadline 9223372036854775807 shifted left 16 bits.
            i2c_test_disp_self[0]->_lf__reaction_1.index = lf_combine_deadline_and_level(9223372036854775807, 2);
        }
    
    }
    

    #ifdef EXECUTABLE_PREAMBLE
    _lf_executable_preamble(&environments[0]);
    #endif
    #ifdef FEDERATED
    initialize_triggers_for_federate();
    #endif // FEDERATED
}
void logical_tag_complete(tag_t tag_to_send) {
 #ifdef FEDERATED_CENTRALIZED
     lf_latest_tag_confirmed(tag_to_send);
 #else
     (void) tag_to_send;
 #endif // FEDERATED_CENTRALIZED

}
#ifndef FEDERATED
void lf_terminate_execution(environment_t* env) {
    (void) env;
}
#endif
